version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    ports:
      - "3307:3306"
    networks:
      - my-network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "9090:80"
    networks:
      - my-network

  induction_server:
    build:
      context: ./gemini-inductions
      dockerfile: Dockerfile
    container_name: induction_server
    restart: always
    ports:
      - "5000:5000"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
